finish girt-rm

diff --git a/girt-rm b/girt-rm
--- a/girt-rm
+++ b/girt-rm
@@ -53,14 +53,16 @@ do
     # fi
 
     # when force is specified, remove file directly
-    if test "$force" = "true" && test "$cache" = "true"
+    if test "$force" = "true"
     then
-        rm "$index"
-    elif test "$force" = "true" && test "$cache" = "false"
-    then
-        rm "$index"
-        rm "$file"
-        # echo "remvoe ${file} in 63"
+        if test "$cache" = "true"
+        then
+            rm "$index"
+        else
+            rm "$index"
+            rm "$file"
+        fi
+        exit 1
     fi
 
     # Do comparison among current directory and index and repository
@@ -85,7 +87,12 @@ do
     # CASE III: file in index is different from working directory but same as in repo
     elif ! cmp -s "$file" "$index" && cmp -s "$index" "$repo"
     then
-        echo "girt-rm: error: '"$file"' in the repository is different to the working file"
+        if test $cached = "true"
+        then
+            rm $index
+        else
+            echo "girt-rm: error: '"$file"' in the repository is different to the working file"
+        fi
    
     # CASE IV : file in three directories are same
     elif cmp -s "$file" "$index" && cmp -s "$index" "$repo"
