pass all autotest

diff --git a/girt-merge b/girt-merge
--- a/girt-merge
+++ b/girt-merge
@@ -8,7 +8,11 @@ then
 fi
 
 # test incorrect input
-if ! test $# = 3 || ! test $2 = "-m" || echo $1 | grep -E -q '^-' || echo $3 | grep -E -q '^-'
+if test $# = 1 && echo $1 | grep -E -q -v '^-'
+then
+    echo "girt-merge: error: empty commit message"
+    exit 1
+elif ! test $# = 3 || ! test $2 = "-m" || echo $1 | grep -E -q '^-' || echo $3 | grep -E -q '^-'
 then
     echo "usage: girt-merge <branch|commit> -m message"
     exit 1
@@ -16,7 +20,7 @@ fi
 
 # get current branch
 branch=$( cat .girt/branch )
-get_last_commit_number() 
+get_last_commit_no() 
 {
     number=0
     while read -r record
@@ -29,6 +33,21 @@ get_last_commit_number()
         fi
     done < .girt/commit
     echo $number
+}
+
+get_branch_name()
+{
+    name=0
+    while read -r record
+    do
+        commit=$(echo "$record" |cut -d' ' -f1)
+        branch=$(echo "$record" |cut -d' ' -f2)
+        if test $commit = $1
+        then
+            name=$(echo $branch)
+        fi
+    done < .girt/commit
+    echo $name
 }
 
 get_common_commit()
@@ -50,16 +69,31 @@ cur_logs=.girt/$branch/logs
 mkdir tmp-merged
 if echo $1 | grep -E -q '^[0-9]$'
 then
-    
+    tar_branch=`get_branch_name $1`
+    if test $tar_branch = 0
+    then
+        echo "girt-merge: error: unknown commit '${1}'"
+        rm -rf tmp-merged
+        exit 1
+    fi
     ############## DEAL WITH MERGE COMMIT ###################
     # first arg is all number => commit number
     # Steps:
     #   1. find out branch the commit conducted
-    #   2. get commit files in target commit folder and load into current 
+    #   2. get commit files in target commit folder and merge into current 
     merge_commit=$1
 
 else
     ############## DEAL WITH MERGE BRANCH ###################
+
+    # check branch exists
+    if ! test -d .girt/$1
+    then
+        echo "girt-merge: error: unknown branch '${1}'"
+        rm -rf tmp-merged
+        exit 1
+    fi
+
     # first arg is not a number => branch name
     # Steps:
     #   1. get bifurcation point of two branches
@@ -68,8 +102,8 @@ else
     tar_index=.girt/$1/index
     tar_wrk=.girt/$1/working 
     tar_logs=.girt/$1/logs
-    cur_lst_cmt=`get_last_commit_number $branch`
-    tar_lst_cmt=`get_last_commit_number $1`
+    cur_lst_cmt=`get_last_commit_no $branch`
+    tar_lst_cmt=`get_last_commit_no $1`
     common=`get_common_commit $branch $1`
     if test $common -eq $cur_lst_cmt
     then
