subset2 9 tests passed

diff --git a/girt-merge b/girt-merge
--- a/girt-merge
+++ b/girt-merge
@@ -45,7 +45,8 @@ merge_message="$3"
 cur_repo=.girt/$branch/repository
 cur_index=.girt/$branch/index
 cur_wrk=.girt/$branch/working
-cur_logs=.girt/logs
+cur_logs=.girt/$branch/logs
+mkdir tmp-merged
 if echo $1 | grep -E -q '^[0-9]$'
 then
     
@@ -62,19 +63,21 @@ else
     # Steps:
     #   1. get bifurcation point of two branches
     #   2. check if last commit number in current branch is larget than the bifurcation point
-    tgt_repo=.girt/$1/repository
-    tgt_index=.girt/$1/index
-    tgt_wrk=.girt/$1/working 
+    tar_repo=.girt/$1/repository
+    tar_index=.girt/$1/index
+    tar_wrk=.girt/$1/working 
+    tar_logs=.girt/$1/logs
     cur_lst_cmt=`get_last_commit_number $branch`
-    tgt_lst_cmt=`get_last_commit_number $1`
+    tar_lst_cmt=`get_last_commit_number $1`
     common=`get_common_commit $branch $1`
     if test $common -eq $cur_lst_cmt
     then
         # FAST FORWARD: no commit created
         rm -rf $cur_repo $cur_index $cur_wrk *
-        cp -R $tgt_repo $cur_repo
-        cp -R $tgt_index $cur_index
-        cp -R $tgt_wrk $cur_wrk
+        cp -R $tar_repo $cur_repo
+        cp -R $tar_index $cur_index
+        cp -R $tar_wrk $cur_wrk
+        cp $tar_logs $cur_logs
         # load file to current working directory
         for file in $cur_wrk/*
         do
@@ -82,8 +85,84 @@ else
         done
         echo "Fast-forward: no commit created"
     else
-        # ERROR: cannot merge
-        echo "girt-merge: error: can not merge"
+        # For the same file in two branches, if one of them is same as the file in the bifuraction commit point
+        # file can be merged => create tmp directory to save the merged repo, keep the last modified file
+        for cur_cmt_file in $cur_repo/*
+        do
+            file=$(echo $cur_cmt_file |rev |cut -d'/' -f1 |rev)
+            common_cmt_file=".girt/${branch}/commit_${common}/${file}"
+            tar_cmt_file="${tar_repo}/${file}"
+            tmp_file="tmp-merged/${file}"
+
+            # CASE VII: file in current repo does not exist in target repo and common repo
+            #           which means the file is added in current commit => save to tmp
+            if ! test -f $tar_cmt_file && ! test -f $common_cmt_file
+            then
+                cp $cur_cmt_file $tmp_file
+            
+            # CASE I:   file only edited in target branch, save target file into tmp
+            elif cmp -s $cur_cmt_file $common_cmt_file && ! cmp -s $tar_cmt_file $common_cmt_file
+            then
+                cp $tar_cmt_file $tmp_file
+            # CASE II:  file only edited in current branch, save current file into tmp
+            elif ! cmp -s $cur_cmt_file $common_cmt_file && cmp -s $tar_cmt_file $common_cmt_file
+            then
+                cp $cur_cmt_file $tmp_file
+            # CASE III: files are still same, save one of them
+            elif cmp -s $cur_cmt_file $tar_cmt_file
+            then
+                cp $cur_cmt_file $tmp_file
+            # CASE IV:  files have different edition => ERROR: cannot merge
+            else
+                echo "girt-merge: error: can not merge"
+                exit 1
+            fi
+        done
+
+        for tar_cmt_file in $tar_repo/*
+        do
+            file=$(echo $tar_cmt_file |rev |cut -d'/' -f1 |rev)
+            common_cmt_file=".girt/${branch}/commit_${common}/${file}"
+            cur_cmt_file="${cur_repo}/${file}"
+            tmp_file="tmp-merged/${file}"
+            # CASE V:   file created in target branch and does not exist in current branch
+            #           will be saved into tmp
+            if ! test -f $common_cmt_file
+            then
+                cp $tar_cmt_file $tmp_file
+            # else ! test -f $common_cmt_file && 
+            fi
+            # CASE VI:  file is deleted from current branch, but still exists in target branch
+            #           should not be merged into tmp => do nothing
+        done
+
+        # update files in current repository folder
+        rm -rf $cur_repo
+        cp -R tmp-merged $cur_repo
+        # update staged file
+        rm -rf $cur_index
+        cp -R tmp-merged $cur_index
+        # update file in current working directory
+        for file in *
+        do
+            if test $file = "tmp-merged"; then continue; fi
+            rm -rf $file
+        done
+        
+        for file in tmp-merged/*
+        do
+            cp $file .
+        done
+        rm -rf tmp-merged
+        # save commit version
+        commit_no=$( cat .girt/commit |wc -l)
+        commit_dir=".girt/${branch}/commit_${commit_no}"
+        cp -R tmp-merged $commit_dir
+        # update commit log and current log
+        echo "Committed as commit ${commit_no}"
+        content="${commit_no} ${merge_message}"
+        echo "${content}" >> .girt/${branch}/logs
+        echo "${commit_no} ${branch}" >> .girt/commit
     fi
 fi
 
